# Generated by Django 3.1.6 on 2021-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futsal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.CharField(max_length=25),
        ),
    ]
