# Generated by Django 3.1.6 on 2021-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futsal', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='uploaded_at',
            field=models.DateField(auto_now=True),
        ),
    ]
