# Generated by Django 3.1.6 on 2021-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futsal', '0006_gallery_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='caption',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
