# Generated by Django 3.1.6 on 2021-03-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futsal', '0007_gallery_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
