# Generated by Django 3.1.6 on 2021-04-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futsal', '0009_auto_20210328_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
