# Generated by Django 3.1.6 on 2021-04-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futsal', '0010_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(max_length=146),
        ),
    ]
