# Generated by Django 3.1.6 on 2021-04-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futsal', '0011_auto_20210402_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/tournament'),
        ),
    ]
